### ISSUE TITLE
More Sites & Application fixes 

### ISSUE THREAD

**Issue by jbecker01** [USSF-ORBIT/ussf-portal-client#302]
Use this issue to log minor UX/UI tweaks we want to fix before using the static site prototype in interviews with users.

To-Do:

- [x] #325
- [ ] The "Delete Collection" link on the far right collection is rendered off the page if your screen size is smaller than the maximum dynamic width of the page
- [ ] #326
- [ ] The "Undo Remove" orange bar could be the same height as the link box it is replacing to avoid the pixel jump that occurs currently
- [ ] The "Select Multiple Collections" button is the only way to add a collection even if you're only adding one; we may want to look at the language on that one to "Select Collection(s)" or something like that
- [x] This very much could be a Netlify-ism: if you add a link that isn't in the autocomplete list, save it and then click the link, you get a 404 error
- [ ] The ability to edit the name of a collection comes when you click the name and is not available in the dropdown of the gear; this may not be obvious to people right away
- [ ] If you click on the "Add Section" button and you're at the bottom of the page, the menu is rendered off screen
- [x] #356

WIP:

Completed:

**Comment by noahfirth** [comment]
@malworks, what are your feelings on the fifth one on the list (it starts with "The "Select Multiple Collections" button". I could be thinking of it incorrectly as well in all fairness.

**Comment by malworks** [comment]
@noahfirth Thank you for starting this! My 2 cents:

Number 2: In the mockup the "delete collection" dropdown is flush right instead of flush left. We can prob just push it over a bit and solve the problem. 
![image](https://user-images.githubusercontent.com/20548582/140815024-e3eb0101-21c3-4c34-8f8f-7fa5ad3c5562.png)

Number 5: Totally agree. "Select Collection(s)" sounds good to me!

Number 7: Agree, see above screenshot for reference.

Number 9: I think "section" indicates the "widget" or box. A section can be a link collection, or a news box.

**Comment by malworks** [comment]
I think I can take a stab at some of these if the engineers are too busy.
